### ISSUE TITLE
[Introductory] Polish pass & new features

### ISSUE THREAD

**Issue by bofhgr** [Legitamine/metanthropes#316]
- [ ] Requires #49 
- [ ] New feature that utilizes v12 Scene Regions #311 (and more..)
- [ ] New Visual Animations and Audio Effects (..we don't want to spoil these just yet)
- [ ] Polish Journal content, including #314 
- [ ] Polish Narrator Toolbox, as well as #302 
- [ ] Roll New Protagonist #315
